webapp/views/about.py
import flask

about_blueprint = flask.Blueprint('about', __name__)

@about_blueprint.route('/about')
def index():
    return flask.render_template('pages/about.html')

webapp/views/contact.py
import flask
import datetime
from webapp.forms import ContactForm
from webapp.forms import flash_errors
from modules.utilities import send_email

contact_blueprint = flask.Blueprint('contact', __name__)

@contact_blueprint.route('/contact', methods=['get', 'post'])
def index():
	form = ContactForm(flask.request.form)
	if form.validate_on_submit():
		send_contact_email(form.name.data, form.email.data, form.comments.data)
		return flask.render_template('pages/thankyou_feedback.html')
	flash_errors(form)
	return flask.render_template('pages/contact.html', form=form)

def _get_email(name, email, comments):
	ret = list()
	ret += ["------------------------------------------------------------"]
	ret += ["\tRecieved feedback at " + datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")]
	ret += ["\t%s (%s) writes: \n" % (name, email)]
	ret += ["\t%s" % comments]
	ret += ["------------------------------------------------------------"]
	return "<br>\n".join(ret)

def send_contact_email(name, email, comments):
	email_body = _get_email(name, email, comments)
	send_email(
		email,
		'guzbit@gmail.com',
		"[Machine Lending] - Contact",
		email_body
	)

webapp/views/forgot.py
from flask import Blueprint, render_template, request
from webapp.forms import ForgotForm
forgot_blueprint = Blueprint('forgot', __name__)

@forgot_blueprint.route('/forgot')
def index():
	form = ForgotForm(request.form)
	return render_template('pages/forgot.html', form=form)

webapp/views/lc.py
import flask
from webapp.models import UsersLCInvestParameters
from modules.utilities import print_log
from flask_login import login_required, current_user

lc_blueprint = flask.Blueprint('lc', __name__)

@lc_blueprint.route('/lc')
def index():
    return flask.render_template('pages/lc.html')

@lc_blueprint.route('/lc/save_invest_params', methods=['post'])
def save_invest_params():
	save_keys = [x for x in dir(UsersLCInvestParameters) if not x.startswith('_')]
	save_params = dict()
	for key in save_keys:
		save_params[key] = flask.request.form.get(key, 0)

	invest_params = UsersLCInvestParameters.get_by_user_id(current_user.id)
	if not invest_params:
		invest_params = UsersLCInvestParameters(
			current_user,
			save_params
		)
		invest_params.commit()
	else:
		UsersLCInvestParameters.update(current_user, save_params)

	invest_params = UsersLCInvestParameters.get_by_user_id(current_user.id)
	flask.flash("Saved Settings.", 'success')

	return flask.render_template('pages/lc.html', error="Saved Settings.")

webapp/views/login.py
import flask
from flask_login import login_user, login_required
from webapp.models import User, UsersLCAccountInfo
from webapp.forms import LoginForm
from webapp.forms import flash_errors
from modules.utilities import print_log

login_blueprint = flask.Blueprint('login', __name__)

@login_blueprint.route('/login', methods=['get', 'post'])
def index():
	form = LoginForm(flask.request.form)
	if form.validate_on_submit():
		username = form.username.data
		password = form.password.data

		user = User.get_by_username(username)

		if user and user.check_password(password):
			login_user(user, remember=False)
			UsersLCAccountInfo.get_lc_account_info(user)
			flask.flash("Logged in.", 'success')
			return flask.redirect(flask.url_for('index.index'))
		else:
			flask.flash("Login error: Wrong username and password combination.", 'danger')

	flash_errors(form)
	return flask.render_template('pages/login.html', form=form)

webapp/views/register.py
import flask
import bcrypt
from flask_login import login_user
from webapp.forms import RegisterForm
from webapp.forms import flash_errors
from webapp.models import User
from modules.utilities import print_log

register_blueprint = flask.Blueprint('register', __name__)

@register_blueprint.route('/register', methods=['get', 'post'])
def index():
	form = RegisterForm(flask.request.form)
	if form.validate_on_submit():
		password = form.password.data.encode('utf-8')
		new_user = User(
			form.username.data,
			bcrypt.hashpw(password, bcrypt.gensalt()),
			form.email.data
		)
		try:
			new_user.commit()
			login_user(new_user, remember=False)
			flask.flash("Signup complete.", 'success')
			return flask.redirect(flask.url_for('settings.lc'))
		except Exception as e:
			flask.flash(str(e), 'danger')

	flash_errors(form)
	return flask.render_template('pages/register.html', form=form)

webapp/templates/pages/about.html
{% extends 'layouts/main.html' %}
{% block title %}About{% endblock %}
{% block content %}

<div class="page-header">
  <h2>About Machine Lending</h2>
</div>
<a target="_blank" href="https://en.wikipedia.org/wiki/Peer-to-peer_lending">Peer-to-peer lending</a>
is a relatively new form of financing, from the people to the people. One of the first, and currently largest,
such lending platforms is <a target="_blank" href="https://www.lendingclub.com/">Lending Club</a>.
More information about Lending Club and democratized lending can be found
<a target="_blank" href="https://www.lendingclub.com/public/how-peer-lending-works.action">here</a>.
<p></p>
Lending Club and other platforms generally have an "Auto-Invest" option to allow
investors to minimally manage their investment. Lending Club, for instance, allows one
to choose a distribution of loan grades in which to invest. However, choosing loans from a distribution of grades
to optimize returns is <b>not trivial or obvious</b>. This is the reason Machine Lending was developed.
<p></p>
The term <i>Machine Lending</i> is ment to describe the fact that the
loan default predictions on this site are calculated using
state-of-the-art machine learning algorithms. The model used to make the predictions
is constantly evolving and improving. See the <a href="#methods">Methods</a> for more details.
<p></p>
<p class="lead">Data</p>
<a name="data"></a>
As any good and transparent corporation would do, Lending Club has made a large amount of historical
data <a target="_blank" href="https://www.lendingclub.com/info/download-data.action">available</a>.
This data ranges from interest rate and <a target="_blank" href="https://en.wikipedia.org/wiki/FICO">FICO</a>
score to the number of months since the borrower was
delinquent and their <a target="_blank" href="http://www.creditcards.com/glossary/term-revolving-balance.php">revolving balance</a>.
Crucially, it also includes the current state of the loans. This means one can see if a loan
was paid in full, charged off, or current. That information is used as the dependent variable
when creating the Lending Club model. Everything else is used to train the models to predict loan default rate.
<p></p>
In addition to historical data, Lending Club also provides information about the current loans that
require funding via their <a target="_blank" href="https://www.lendingclub.com/developers/lc-api.action">API</a>. This enables
algorithmic prediction and purchase of the cream-of-the-crop notes.
<p></p>
<a name="methods"></a>
<p class="lead">Methods</p>
To make loan default predictions, Machine Lending uses what is called
<a target="_blank" href="https://en.wikipedia.org/wiki/Ensemble_learning">ensemble learning</a>.
In short, take a set of the appropriate machine learning algorithms and optimize
their coordination to fit the historical data as best possible. It's a
"<a target="_blank" href="https://en.wikipedia.org/wiki/The_Wisdom_of_Crowds">wisdom of crowds</a>"
approach to machine learning. This approach of combining the predictions of different algorithms is generally the winning
solution to black-box style machine learning competions, such as the
<a target="_blank" href="https://www.kaggle.com/c/otto-group-product-classification-challenge/forums/t/14335/1st-place-winner-solution-gilberto-titericz-stanislav-semenov/79599">Kaggle OTTO</a> challenge.
Machine Lending uses an optimized linear combination of predictions from the following algorithms:<br>
<a target="_blank" href="http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html">Random Forest, sklearn</a><br>
<a target="_blank" href="http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesClassifier.html">Extra Trees, sklearn</a><br>
<a target="_blank" href="http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html">Gradient Boosting Classifier, sklearn</a><br>
<a target="_blank" href="http://scikit-learn.org/dev/modules/generated/sklearn.neural_network.MLPClassifier.html">Multi Layer Perceptron Classifier, sklearn</a><br>
<a target="_blank" href="http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html">K Neighbors Classifier, sklearn</a><br>
<a target="_blank" href="https://github.com/dmlc/xgboost">Extreme Gradient Boosting, xgboost</a><br>
<a target="_blank" href="https://keras.io/">Keras Neural Network, Keras</a><br>
<!--<a target="_blank" href="https://github.com/Lasagne/Lasagne">Lasane Neural Network, Lasange</a><br>-->

Source code for the MetaClassifier is available on
<a target="_blank" href="https://github.com/uzbit/mlutils">github</a>.
<p></p>
The features used to make the data set include 44 of the columns from the historical data plus engineered features.
Some of the engineered features utilize zip_code to lookup information about the region from the 2014 Census as well as Zillow housing
information. By removing the loan_status and using it as the dependent variable, as well as removing columns that do not
populate more than one quartile, we end up with 109 feature columns in total. <b>Currently the model only uses data for
36 month terms</b>. Extending this to other term lengths is future work.
<p></p>
<p class="lead">Results</p>
<a name="results"></a>
A commonly used metric to determine the performance of a binary classifier is the area under the
<a href="https://en.wikipedia.org/wiki/Receiver_operating_characteristic">Receiver Operating Characteristic</a> (ROC) curve.
Generally, a classifier has an area under the curve (auc) somewhere between 0.5 and 1.0. Values closer to 1.0 indicate stronger
predictive power. Below is a plot of the current ROC curve for the Machine Lending classifier, with auc = 0.90. Plotted is the mean (red)
and ± 3 standard deviations (blue) ROC curves for 10 fold training cross-validation sets.
<script type="text/javascript" src="/static/plots/roc_auc_var.js"></script>
<script type="text/javascript" src="/static/plots/roc_auc_var.div.js"></script>
<p></p>
To get an idea of how the features are used, on can pull the relative feature importances from the tree based models (xgboost, ExtraTreesClassifier, etc.)
and plot their relative importance. Below is a plot of the average feature importances for the tree based models.
<script type="text/javascript" src="/static/plots/feature_importance.js"></script>
<script type="text/javascript" src="/static/plots/feature_importance.div.js"></script>
<p></p>
Since the model doesn't directly use grade, subgrade, or interest rate as input, it's nice to see that the grades match up well
with the default probabilities. In the <a href="https://en.wikipedia.org/wiki/Box_plot">box plot</a> below, the distribution of default probabilities by grade is shown.
The wiskers are at ±1.5 <a href="https://en.wikipedia.org/wiki/Interquartile_range">IQR</a>.
<script type="text/javascript" src="/static/plots/default_probability_by_grade.js"></script>
<script type="text/javascript" src="/static/plots/default_probability_by_grade.div.js"></script>

<p class="lead">Disclaimer</p>
The content included in this Website has been compiled from a variety of sources and is subject to change without notice as are any products, programs, offerings, or technical information described in this Website.
Machine Lending makes no representation or warranty whatsoever regarding the completeness, quality, or adequacy of the Website or content, or the suitability, functionality, or operation of this web site or its content.
By using this Website, you assume the risk that the content on this Website may be inaccurate, incomplete, or offensive or may not meet your needs and requirements.
Machine Lending specifically disclaims all warranties, express or implied, including without limitation the warranties of merchantability, fitness for a particular purpose, and non-infringement with respect to this Website.
In no event will the Machine Lending be liable for any special, indirect, incidental or consequential damages even if company has been advised of the possibility of such damages.
<p></p>

{% endblock %}

webapp/templates/pages/forgot.html
{% extends 'layouts/main.html' %}
{% block title %}Reset Password{% endblock %}
{% block content %}
<div class="well bs-component col-lg-6 " style="margin-top: 30px;">
  <form method="post" class="form-horizontal">
    <h3 class="form-heading">Reset Password</h3> <!--<a href="{{ url_for('index.index') }}" title="Back to homepage"><i class="fa fa-home pull-right"></i></a>-->
    {{ form.email(class_ = 'form-control first-input last-input', placeholder = form.email.label.text) }}
    <p class="pull-left"><a href="{{ url_for('login.index') }}">Login</a></p>
    <p class="pull-right"><a href="{{ url_for('register.index') }}">Register</a></p>
    <input type="submit" value="Submit" class="btn btn-lg btn-primary btn-block" disabled>
	</form>
</div>

{% endblock %}

webapp/templates/pages/general_error.html
{% extends 'layouts/main.html' %}
{% block title %}Error{% endblock %}
{% block content %}

<div class="page-header">
  <h2>Error</h2>
</div>

<h3>Something went wrong!</h3>

{% endblock %}

webapp/templates/pages/home.html
{% extends 'layouts/main.html' %}
{% block title %}Machine Lending{% endblock %}
{% block content %}

<div class="page-header">
  <h2>Welcome to Machine Lending</h2>
</div>
<p class="lead">Increasing p2p lending returns by leveraging data and cutting-edge machine learning techniques.</p>
<a href="/lc" class="btn btn-primary">View Predicitons</a> <a href="/about" class="btn btn-success">Learn More</a>

{% endblock %}

webapp/templates/pages/lc.html
{% extends 'layouts/main.html' %}
{% block title %}Lending Club{% endblock %}
{% block content %}


<script type="text/javascript" src="/static/js/lc.js" defer></script>
<script type="text/javascript" src="/static/js/utilities.js"></script>
<script type="text/javascript" src="/static/js/lc_simulate.js"></script>
<script type="text/javascript" src="/static/js/lc_invest.js"></script>
<!--
http://plnkr.co/edit/DdHLjgjK23KF8fJd1gMw?p=preview
-->
<!-- <div class="page-header">
  <h2>Lending Club Loans</h2>
</div> -->

<ul class="nav nav-tabs" style="margin-top:30px;">
	<li {% if request.endpoint == 'lc.index' %} class="active" {% endif %}>
		<a href="#lc_current" data-toggle="tab">Current Loans</a>
	</li>
	<li {% if request.endpoint == 'lc#lc_simulate' %} class="active" {% endif %}>
		<a href="#lc_simulate" data-toggle="tab">Simluate</a>
	</li>
	<li {% if request.endpoint == 'lc#lc_invest' %} class="active" {% endif %}>
		<a href="#lc_invest" data-toggle="tab">Invest</a>
	</li>
	<li {% if request.endpoint == 'lc#lc_confirmation' %} class="active" {% endif %}>
		<a href="#lc_confirmation" data-toggle="tab" class="disableClick">Confirmation</a>
	</li>
</ul>

<div id="tabContent" class="tab-content">
	<div id="lc_current" class="tab-pane fade active in" >
		<div style="margin-top:30px;">
			<table id="lcCurrentTable" class="display" width="100%"></table>
			<div id="lcAsOfDate">Loading...</div>
		</div>
	</div>

	<div id="lc_simulate" class="tab-pane fade" style="margin-bottom: 30px; margin-top:30px;">
		{% include "partials/lc_simulate.html" %}
	</div>

	<div id="lc_invest" class="tab-pane fade" style="margin-bottom: 30px; margin-top:30px;">
		{% include "partials/lc_invest.html" %}
	</div>

	<div id="lc_confirmation" class="tab-pane fade" style="margin-bottom: 30px; margin-top:30px;">
		{% include "partials/lc_confirmation.html" %}
	</div>
</div>

{% endblock %}

webapp/templates/pages/lc_account.html
{% extends 'layouts/settings.html' %}
{% block title %}Lending Club Account Info{% endblock %}
{% block content %}
{{ super() }}


<div class="alert alert-dismissible alert-info" style="margin-top: 30px; float: right;clear: right;">
<button type="button" class="close" data-dismiss="alert">&times;</button>
This information is encrypted before it's stored.
</div>
<div class="well bs-component col-lg-6" style="margin-top: 30px; float: left;clear: left;">
  <form method="post" class="form-horizontal">
  <h3 class="form-heading">Lending Club Account Information</h3>
	{{ form.api_key(class_ = 'form-control', placeholder = form.api_key.label.text, autofocus = true) }}
	{{ form.account_number(class_ = 'form-control', placeholder = form.account_number.label.text) }}
	{{ form.portfolio_name(class_ = 'form-control', placeholder = form.portfolio_name.label.text) }}
	{% if current_user.is_subscription_valid() %}
    <table border='0' padding="10px"><tr>
    <td>{{ form.auto_invest.label }}</td><td>{{ form.auto_invest(placeholder = form.auto_invest.label.text) }}</td>
    </tr></table>
	{% endif %}

	<input type="submit" value="Save" class="btn btn-primary">
</form>


{% endblock %}

webapp/templates/pages/login.html
{% extends 'layouts/main.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="well bs-component col-lg-6" style="margin-top: 30px;float: left;clear: left;">
  <form method="post" class="form-horizontal">
    <h3 class="form-heading">Login</h3> <!--<a href="{{ url_for('index.index') }}" title="Back to homepage"><i class="fa fa-home pull-right"></i></a>-->
    {{ form.username(class_ = 'form-control first-input', placeholder = form.username.label.text, required = true, autofocus = true) }}
    {{ form.password(class_ = 'form-control last-input', placeholder = form.password.label.text, required = true) }}
    <!-- <p class="pull-left"><a href="{{ url_for('forgot.index') }}">Forgot Password?</a></p>
    <p class="pull-right"><a href="{{ url_for('register.index') }}">Register</a></p> -->
    <input type="submit" value="Submit" class="btn btn-primary btn-lg btn-block">
  </form>
</div>
{% endblock %}

webapp/templates/pages/ml_account.html
{% extends 'layouts/settings.html' %}
{% block title %}Machine Lending Account Info{% endblock %}
{% block content %}
{{ super() }}

<div class="well bs-component col-lg-6" style="margin-top: 30px; float: left; clear: left;">
	<h3>Manage Your Subscription</h3>
	<a name="manage_subscription"></a>
{% if current_user.is_subscription_valid() %}
Current Subscription - Basic Monthly<br>
<a href="/subscriptions/cancel" class="btn btn-primary">Cancel Subscription</a>
{% else %}
Buy $1.99 per month basic subscription:
<form method="post" action="/subscriptions" enctype='application/json'>
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_FK8eQlJpN56LaiwHcvDBdD1t"
    data-amount="199"
    data-name="Monthly Subscription"
    data-description="Recurring $1.99/month for auto-investing."
		data-locale="auto"
		data-zip-code="true">
  </script>
	<input type="hidden" name="plan" value="basic_monthly_subscription"></input>
</form>
<h6>Subscriptions are securely managed by <a href="https://stripe.com/">Stripe</a>.</h6>

{% endif %}
</div>

<div class="well bs-component col-lg-6" style="margin-top: 30px; float: left; clear: left;">

	<form method="post" class="form-horizontal">
      <h3 class="form-heading">Update Account Information</h3> <!--<a href="{{ url_for('index.index') }}" title="Back to homepage"><i class="fa fa-home pull-right"></i></a>-->
      {{ form.email(class_ = 'form-control', placeholder = form.email.label.text) }}
      {{ form.password(class_ = 'form-control', placeholder = "New Password") }}
      {{ form.confirm(class_ = 'form-control last-input', placeholder = "Repeat New Password") }}
			<input type="submit" value="Update" class="btn btn-primary" >
  </form>
</div>


{% endblock %}

webapp/templates/pages/register.html
{% extends 'layouts/main.html' %}
{% block title %}Register{% endblock %}
{% block content %}
<div class="well bs-component col-lg-6" style="margin-top: 30px; float: left; clear: left;">
  <form method="post" class="form-horizontal">
      <h3 class="form-heading">Register</h3> <!--<a href="{{ url_for('index.index') }}" title="Back to homepage"><i class="fa fa-home pull-right"></i></a>-->
      {{ form.username(class_ = 'form-control first-input', placeholder = form.username.label.text, required = true, autofocus = true) }}
      {{ form.email(class_ = 'form-control', placeholder = form.email.label.text, required = true) }}
      {{ form.password(class_ = 'form-control', placeholder = form.password.label.text, required = true) }}
      {{ form.confirm(class_ = 'form-control last-input', placeholder = form.confirm.label.text, required = true) }}
      {{ form.recaptcha }}
			<!-- <p class="pull-left"><a href="{{ url_for('login.index') }}">Login</a></p> -->
			<input type="submit" value="Register" class="btn btn-primary btn-lg btn-block">
	</form>
</div>

{% endblock %}

webapp/templates/pages/thankyou.html
{% extends 'layouts/main.html' %}
{% block title %}Lending Club{% endblock %}
{% block content %}

<div class="page-header">
  <h2>Contact</h2>
</div>

<h3>Thank you for the feedback!</h3>
<a href="/lc" class="btn btn-primary">View Predicitons</a>
{% endblock %}

webapp/templates/pages/thankyou_feedback.html
{% extends 'layouts/main.html' %}
{% block title %}Contact{% endblock %}
{% block content %}

<div class="page-header">
  <h2>Contact</h2>
</div>

<h3>Thank you for the feedback!</h3>
<a href="/lc" class="btn btn-primary">View Predicitons</a>
{% endblock %}

webapp/templates/pages/thankyou_subscriptions.html
{% extends 'layouts/main.html' %}
{% block title %}Machine Lending{% endblock %}
{% block content %}

<div class="page-header">
  <h2>Subscriptions</h2>
</div>

<h3>Thank you for subscribing!</h3>
<a href="/lc" class="btn btn-primary">Manage Investment</a>
{% endblock %}